/*
    Enables or disables a privilege in the current process.
    Parameters:
        Privilege:
            Privileges determine the type of system operations that a user account can perform.
            This parameter must be one of the following privilege values.
            ┌───────┬───────────────────────────────────────────┬───────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────┐
            │ Value │ Constant                                  │ Text                                      │ Meaning                                                                                                                                                               │ Enabled                                                                        │
            ├───────┼───────────────────────────────────────────┼───────────────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┼────────────────────────────────────────────────────────────────────────────────┤
            │ 0     │ SE_UNSOLICITED_INPUT_NAME                 │ SeUnsolicitedInputPrivilege               │ Required to read unsolicited input from a terminal device. User Right: Not applicable.                                                                                │                                                                                │
            │ 2     │ SE_CREATE_TOKEN_NAME                      │ SeCreateTokenPrivilege                    │ Required to create a primary token. User Right: Create a token object.                                                                                                │                                                                                │
            │ 3     │ SE_ASSIGNPRIMARYTOKEN_NAME                │ SeAssignPrimaryTokenPrivilege             │ Required to assign the primary token of a process. User Right: Replace a process-level token.                                                                         │                                                                                │
            │ 4     │ SE_LOCK_MEMORY_NAME                       │ SeLockMemoryPrivilege                     │ Required to lock physical pages in memory. User Right: Lock pages in memory.                                                                                          │                                                                                │
            │ 5     │ SE_INCREASE_QUOTA_NAME                    │ SeIncreaseQuotaPrivilege                  │ Required to increase the quota assigned to a process. User Right: Adjust memory quotas for a process.                                                                 │                                                                                │
            │ 6     │ SE_MACHINE_ACCOUNT_NAME                   │ SeMachineAccountPrivilege                 │ Required to create a computer account. User Right: Add workstations to domain.                                                                                        │                                                                                │
            │ 7     │ SE_TCB_NAME                               │ SeTcbPrivilege                            │ This privilege identifies its holder as part of the trusted computer base. User Right: Act as part of the operating system.                                           │                                                                                │
            │ 8     │ SE_SECURITY_NAME                          │ SeSecurityPrivilege                       │ Required to perform a number of security-related functions. User Right: Manage auditing and security log.                                                             │                                                                                │
            │ 9     │ SE_TAKE_OWNERSHIP_NAME                    │ SeTakeOwnershipPrivilege                  │ Required to take ownership of an object without being granted discretionary access. User Right: Take ownership of files or other objects.                             │                                                                                │
            │ 10    │ SE_LOAD_DRIVER_NAME                       │ SeLoadDriverPrivilege                     │ Required to load or unload a device driver. User Right: Load and unload device drivers.                                                                               │                                                                                │
            │ 11    │ SE_SYSTEM_PROFILE_NAME                    │ SeSystemProfilePrivilege                  │ Required to gather profiling information for the entire system. User Right: Profile system performance.                                                               │                                                                                │
            │ 12    │ SE_SYSTEMTIME_NAME                        │ SeSystemtimePrivilege                     │ Required to modify the system time. User Right: Change the system time.                                                                                               │                                                                                │
            │ 13    │ SE_PROF_SINGLE_PROCESS_NAME               │ SeProfileSingleProcessPrivilege           │ Required to gather profiling information for a single process. User Right: Profile single process.                                                                    │                                                                                │
            │ 14    │ SE_INC_BASE_PRIORITY_NAME                 │ SeIncreaseBasePriorityPrivilege           │ Required to increase the base priority of a process. User Right: Increase scheduling priority.                                                                        │                                                                                │
            │ 15    │ SE_CREATE_PAGEFILE_NAME                   │ SeCreatePagefilePrivilege                 │ Required to create a paging file. User Right: Create a pagefile.                                                                                                      │                                                                                │
            │ 16    │ SE_CREATE_PERMANENT_NAME                  │ SeCreatePermanentPrivilege                │ Required to create a permanent object. User Right: Create permanent shared objects.                                                                                   │                                                                                │
            │ 17    │ SE_BACKUP_NAME                            │ SeBackupPrivilege                         │ Required to perform backup operations. User Right: Back up files and directories.                                                                                     │                                                                                │
            │ 18    │ SE_RESTORE_NAME                           │ SeRestorePrivilege                        │ Required to perform restore operations. User Right: Restore files and directories.                                                                                    │                                                                                │
            │ 19    │ SE_SHUTDOWN_NAME                          │ SeShutdownPrivilege                       │ Required to shut down a local system. User Right: Shut down the system.                                                                                               │                                                                                │
            │ 20    │ SE_DEBUG_NAME                             │ SeDebugPrivilege                          │ Required to debug and adjust the memory of a process owned by another account. User Right: Debug programs.                                                            │                                                                                │
            │ 21    │ SE_AUDIT_NAME                             │ SeAuditPrivilege                          │ Required to generate audit-log entries. User Right: Generate security audits.                                                                                         │                                                                                │
            │ 22    │ SE_SYSTEM_ENVIRONMENT_NAME                │ SeSystemEnvironmentPrivilege              │ Required to modify the nonvolatile RAM of systems that use this type of memory to store configuration information. User Right: Modify firmware environment values.    │                                                                                │
            │ 23    │ SE_CHANGE_NOTIFY_NAME                     │ SeChangeNotifyPrivilege                   │ Required to receive notifications of changes to files or directories. User Right: Bypass traverse checking.                                                           │ Enabled by default for all users.                                              │
            │ 24    │ SE_REMOTE_SHUTDOWN_NAME                   │ SeRemoteShutdownPrivilege                 │ Required to shut down a system using a network request. User Right: Force shutdown from a remote system.                                                              │                                                                                │
            │ 25    │ SE_UNDOCK_NAME                            │ SeUndockPrivilege                         │ Required to undock a laptop. User Right: Remove computer from docking station.                                                                                        │                                                                                │
            │ 26    │ SE_SYNC_AGENT_NAME                        │ SeSyncAgentPrivilege                      │ Required for a domain controller to use the Lightweight Directory Access Protocol directory synchronization services. User Right: Synchronize directory service data. │                                                                                │
            │ 27    │ SE_ENABLE_DELEGATION_NAME                 │ SeEnableDelegationPrivilege               │ Required to mark user and computer accounts as trusted for delegation. User Right: Enable computer and user accounts to be trusted for delegation.                    │                                                                                │
            │ 28    │ SE_MANAGE_VOLUME_NAME                     │ SeManageVolumePrivilege                   │ Required to enable volume management privileges. User Right: Manage the files on a volume.                                                                            │                                                                                │
            │ 29    │ SE_IMPERSONATE_NAME                       │ SeImpersonatePrivilege                    │ Required to impersonate. User Right: Impersonate a client after authentication.                                                                                       │                                                                                │
            │ 30    │ SE_CREATE_GLOBAL_NAME                     │ SeCreateGlobalPrivilege                   │ Required to create named file mapping objects in the global namespace during Terminal Services sessions. User Right: Create global objects.                           │ Enabled by default for administrators, services, and the local system account. │
            │ 31    │ SE_TRUSTED_CREDMAN_ACCESS_NAME            │ SeTrustedCredManAccessPrivilege           │ Required to access Credential Manager as a trusted caller. User Right: Access Credential Manager as a trusted caller.                                                 │                                                                                │
            │ 32    │ SE_RELABEL_NAME                           │ SeRelabelPrivilege                        │ Required to modify the mandatory integrity level of an object. User Right: Modify an object label.                                                                    │                                                                                │
            │ 33    │ SE_INC_WORKING_SET_NAME                   │ SeIncreaseWorkingSetPrivilege             │ Required to allocate more memory for applications that run in the context of users. User Right: Increase a process working set.                                       │                                                                                │
            │ 34    │ SE_TIME_ZONE_NAME                         │ SeTimeZonePrivilege                       │ Required to adjust the time zone associated with the computer's internal clock. User Right: Change the time zone.                                                     │                                                                                │
            │ 35    │ SE_CREATE_SYMBOLIC_LINK_NAME              │ SeCreateSymbolicLinkPrivilege             │ Required to create a symbolic link. User Right: Create symbolic links.                                                                                                │                                                                                │
            │ 36    │ SE_DELEGATE_SESSION_USER_IMPERSONATE_NAME │ SeDelegateSessionUserImpersonatePrivilege │ Required to obtain an impersonation token for another user in the same session. User Right: Impersonate other users.                                                  │                                                                                │
            └───────┴───────────────────────────────────────────┴───────────────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────┘
            Reference: (https://docs.microsoft.com/en-us/windows/win32/secauthz/privilege-constants).
        Disable:
            ┌───────┬───────────────────────────────────────┐
            │ Value │ Meaning                               │
            ├───────┼───────────────────────────────────────┤
            │ TRUE  │  The function disables the privilege. │
            │ FALSE │  The function enables the privilege.  │
            └───────┴───────────────────────────────────────┘
        CurrentThread:
            ┌───────┬────────────────────────────────────────────────────────────┐
            │ Value │ Meaning                                                    │
            ├───────┼────────────────────────────────────────────────────────────┤
            │ TRUE  │ The function enables the privilege in the calling thread.  │
            │ FALSE │ The function enables the privilege in the calling process. │
            └───────┴────────────────────────────────────────────────────────────┘
    Return value:
        If the function succeeds, the return value is the previous privilege state (0/1).
        If the function fails, the return value is <0. A_LastError contains extended error information (NTSTATUS).
*/
AdjustPrivilege(Privilege, Disable := FALSE, CurrentThread := FALSE)
{
    local Enabled  := 0
    local NtStatus := DllCall("Ntdll.dll\RtlAdjustPrivilege",   "UInt", Privilege        ; ULONG          Privilege.
                                                            ,  "UChar", !Disable         ; BOOLEAN        Enable.
                                                            ,  "UChar", !!CurrentThread  ; BOOLEAN        CurrentThread.
                                                            , "UCharP", Enabled          ; (out)PBOOLEAN  Enabled.
                                                            , "UInt")                    ; NTSTATUS       ReturnValue.
    if (NtStatus)
        A_LastError := NtStatus
    return NtStatus ? -NtStatus : Enabled
} ; https://source.winehq.org/WineAPI/RtlAdjustPrivilege.html
